version: "3"

vars:
  DOCKER_IMAGE: daromi/chirp-core

tasks:
  default:
    cmd: task -a

  clean:
    cmd: ./gradlew clean

  test:
    cmd: ./gradlew test

  build:jar:
    deps:
      - clean
    cmd: ./gradlew bootJar

  build:docker:
    deps:
      - build:jar
    cmd: docker build -t {{.DOCKER_IMAGE}}:latest .

  local:shell:run:
    cmd: ./gradlew bootRun
