version: "3"

tasks:
  default:
    cmd: task -a

  clean:
    cmd: ./gradlew clean

  test:
    cmd: ./gradlew test

  build:
    deps:
      - clean
    cmd: ./gradlew bootJar

  package:
    deps:
      - build
    vars:
      DOCKER_IMAGE: daromi/chirp-core
    cmd: docker build -t {{.DOCKER_IMAGE}}:latest .

  local:run:
    cmd: ./gradlew bootRun

  local:ping:
    vars:
      PORT: 8080
    cmd: curl -v localhost:{{.PORT}}/ping
